import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: {
      home: 'Home', ewasteInfo: 'E-Waste Info', dropoffMap: 'Drop-off Map',
      updates: 'Updates', register: 'Register', incentives: 'Incentives',
      login: 'Login', myAccount: 'My Account',
    },
    home: {
      heroTitle: 'E-Cycle Hub',
      heroTagline: 'Responsibly recycle your e-waste and earn rewards while protecting our environment',
      registerBtn: 'Register Drop-off', learnMoreBtn: 'Learn More',
      whyTitle: 'Why E-Cycle Hub?',
      feature1Title: 'Protect Environment', feature1Desc: 'Prevent toxic e-waste from contaminating our soil and water',
      feature2Title: 'Earn Rewards', feature2Desc: 'Get ₱5 per kilogram of e-waste you responsibly recycle',
      feature3Title: 'Circular Economy', feature3Desc: 'Help recover valuable materials for reuse and manufacturing',
      feature4Title: 'Community Impact', feature4Desc: 'Join thousands making a difference in our barangay',
      quickAccessTitle: 'Quick Access',
      link1Title: 'Learn About E-Waste', link1Desc: 'Understand why e-waste matters',
      link2Title: 'Find Drop-off Points', link2Desc: 'Locate nearest collection center',
      link3Title: 'Register E-Waste', link3Desc: 'Start your recycling journey',
      link4Title: 'View Rewards', link4Desc: 'See how much you can earn',
    },
    login: {
      welcomeBack: 'Welcome Back',
      subtitle: 'Sign in to track your e-waste drops and earn rewards',
      usernameLabel: 'Username', usernamePlaceholder: 'Enter your username',
      passwordLabel: 'Password', passwordPlaceholder: 'Enter your password',
      signInBtn: 'Sign In', signingIn: 'Signing in...',
      noAccount: "Don't have an account?", registerHere: 'Register here',
      featuresTitle: 'Features',
      feature1: 'Track e-waste drops', feature2: 'Monitor rewards earned', feature3: 'View collection history',
      trackImpact: '📊 Track Impact', trackImpactDesc: 'Monitor your e-waste drops and rewards',
      earnRewards: '💰 Earn Rewards', earnRewardsDesc: 'Get ₱5 per kilogram of e-waste',
      helpEnv: '🌍 Help Environment', helpEnvDesc: 'Be part of the solution',
    },
    register: {
      titleLoggedIn: 'Report E-Waste', titleNew: 'Register - E-Cycle Hub',
      ewasteSection: 'E-Waste Details', optional: '(Optional)',
      optionalNote: 'You can report e-waste now or later from your dashboard.',
      selectDropoff: 'Select Drop-off Location', weight: 'Weight (kg)', selectEwaste: 'Select E-Waste Type',
      accountSection: 'Account Credentials (Required)',
      firstName: 'First Name *', lastName: 'Last Name *', username: 'Username *',
      email: 'Email *', password: 'Password *', confirmPassword: 'Confirm Password *',
      securityAnswer: 'Security Answer *',
      consent: 'I agree to the e-waste processing terms.',
      submitEwaste: 'Submit E-Waste Record', completeReg: 'Complete Registration', processing: 'Processing...',
    },
    dashboard: {
      title: 'Dashboard', welcome: 'Welcome,', logout: 'Logout',
      logoutConfirm: 'Logout?', logoutText: 'Are you sure you want to logout?', logoutYes: 'Yes, logout',
      totalDrops: 'Total Drops', ewasteItems: 'e-waste items',
      totalWeight: 'Total Weight', recycled: 'recycled',
      totalRewards: 'Total Rewards', earned: 'earned',
      envImpact: 'Environmental Impact', co2Saved: 'kg CO₂ saved',
      dropHistory: 'Your Drop History',
      noDrops: 'No e-waste submissions yet.', noDropsHint: 'Use the New Drop-off button to get started!',
      type: 'Type', weight: 'Weight', date: 'Date', location: 'Location', reward: 'Reward', status: 'Status',
      quickActions: 'Quick Actions',
      newDropoff: 'New Drop-off', newDropoffDesc: 'Register e-waste',
      findLocation: 'Find Location', findLocationDesc: 'Nearest drop-off',
      viewRewards: 'View Rewards', viewRewardsDesc: 'Reward details',
      updates: 'Updates', updatesDesc: 'Latest news',
    },
    updates: {
      title: 'Collection Updates & Announcements',
      subtitle: 'Stay informed about collection schedules and important notices',
      all: 'All Updates', collection: 'Collection', notices: 'Notices', announcements: 'Announcements',
      noAnnouncements: 'No announcements at this time. Check back soon!',
      tip: '💡 Tip:', tipText: 'Follow our Barangay Facebook page for real-time updates and announcements.',
    },
    education: {
      title: 'What is E-Waste?',
      subtitle: 'Learn about electronic waste and why responsible recycling matters',
      faq1Q: 'Why is e-waste harmful?',
      faq1A: 'E-waste contains toxic materials like lead, mercury, and cadmium that can contaminate soil and water. When improperly disposed, these toxins harm ecosystems and human health. Improper burning releases harmful gases, and landfills leak chemicals into groundwater. Responsible recycling prevents environmental damage and recovers valuable materials.',
      faq2Q: 'What happens when e-waste is recycled properly?',
      faq2A: 'Proper recycling recovers valuable materials like gold, copper, and rare earth elements for reuse. Toxic components are safely handled and disposed of. This reduces mining needs, saves energy, and prevents environmental pollution. Recycled materials are used to manufacture new electronics, creating a circular economy and reducing waste in landfills.',
      faq3Q: 'Did you know?',
      faq3A: 'One million smartphones contain 35 times more copper than one ton of copper ore. Recycling one million laptops saves the energy equivalent of powering 3,500 homes for a year. E-waste is the fastest-growing waste stream globally, with over 50 million tons generated annually.',
      stat1Title: '50+ Million Tons', stat1Desc: 'E-waste generated globally per year',
      stat2Title: '₱57 Billion', stat2Desc: 'Value of materials in global e-waste',
      stat3Title: '3,500 Homes', stat3Desc: 'Energy saved by recycling 1M laptops yearly',
    },
    map: {
      title: 'Drop-off Locations',
      subtitle: 'Find the nearest collection point and check schedules',
      locations: 'Locations',
      allLocations: 'All Locations',
      loading: 'Loading map...',
      address: 'Address',
      schedule: 'Schedule',
      tip: '📢 Tip:', tipText: 'Check our updates page for schedule changes and announcements.',
    },
    incentives: {
      title: 'Incentives & Rewards ♻️',
      subtitle: 'Earn rewards for every kilogram of e-waste you responsibly recycle in Barangay Burol 1',
      rewardTitle: 'Reward Program',
      rewardUnit: 'per kilogram of e-waste',
      rewardDesc: 'For every 1 kilogram of e-waste you drop off, you earn ₱5 or an equivalent voucher that can be used for community services.',
      howToTitle: 'How to Claim',
      step1: 'Register your e-waste drop-off through our form',
      step2: 'Provide accurate weight information',
      step3: 'Receive your reward certificate',
      step4: 'Claim your ₱5 voucher per kilogram at the Barangay Hall',
      step5: 'Use your voucher for community programs or services',
      termsTitle: 'Terms & Conditions',
      term1: 'Rewards are valid for 12 months from issuance',
      term2: 'Minimum weight for reward claim: 0.5 kg',
      term3: 'Accepted: Phones, Laptops, Chargers, and Batteries',
      term4: 'One registration per drop-off session',
      term5: 'Vouchers are non-transferable and non-refundable',
      term6: 'Barangay reserves the right to verify e-waste condition',
      calcTitle: 'Calculate Your Reward 💰',
      calcLabel: 'Enter weight (kg):',
      calcBtn: 'Calculate',
      calcWeight: 'Weight:', calcRate: 'Rate:', calcTotal: 'Total Reward:',
      tip: '💡 Tip:', tipText: 'Collect e-waste from your family and friends in Burol 1 to maximize your rewards! Every kilogram counts.',
      invalidWeight: 'Please enter a valid weight in kilograms',
    },
    adminLogin: {
      title: 'Admin Access',
      subtitle: 'Barangay Burol 1 — Restricted Area',
      usernamePlaceholder: 'Admin Username',
      passwordPlaceholder: 'Admin Password',
      loginBtn: 'Login',
      verifying: 'Verifying...',
    },
    footer: {
      tagline: 'Promoting responsible e-waste recycling and environmental sustainability in our community.',
      contactTitle: 'Contact Information',
      location: 'Location', locationValue: 'Burol 1 Dasmarinas Cavite',
      phone: 'Phone',
      barangayHall: 'Barangay Hall', barangayHallValue: 'Burol 1 Dasmarinas Cavite',
      followUs: 'Follow Us',
      socialText: 'Visit our Barangay Facebook page for updates and announcements',
      partners: 'Partners',
      partner1: 'Barangay Government', partner2: 'Environmental Office', partner3: 'Community Organizations',
      disclaimer: 'Disclaimer:', disclaimerText: 'This website provides information about e-waste recycling and collection services. For official announcements and updates, please refer to the Barangay Hall or official social media channels.',
      poweredBy: 'Powered by:', copyright: '© 2024 E-Cycle Hub. All rights reserved.',
    },
  },

  fil: {
    nav: {
      home: 'Tahanan', ewasteInfo: 'Impormasyon sa E-Waste', dropoffMap: 'Mapa ng Drop-off',
      updates: 'Mga Update', register: 'Mag-rehistro', incentives: 'Mga Insentibo',
      login: 'Mag-login', myAccount: 'Aking Account',
    },
    home: {
      heroTitle: 'E-Cycle Hub',
      heroTagline: 'Responsableng i-recycle ang iyong e-waste at kumita ng gantimpala habang pinoprotektahan ang ating kalikasan',
      registerBtn: 'Mag-rehistro ng Drop-off', learnMoreBtn: 'Matuto Pa',
      whyTitle: 'Bakit E-Cycle Hub?',
      feature1Title: 'Protektahan ang Kalikasan', feature1Desc: 'Pigilan ang nakakalason na e-waste mula sa pagkontamina ng ating lupa at tubig',
      feature2Title: 'Kumita ng Gantimpala', feature2Desc: 'Makakuha ng ₱5 bawat kilo ng e-waste na iyong responsableng ini-recycle',
      feature3Title: 'Circular Economy', feature3Desc: 'Tumulong sa pagbawi ng mahahalagang materyales para sa muling paggamit',
      feature4Title: 'Epekto sa Komunidad', feature4Desc: 'Samahan ang libu-libo na gumagawa ng pagbabago sa ating barangay',
      quickAccessTitle: 'Mabilis na Access',
      link1Title: 'Matuto Tungkol sa E-Waste', link1Desc: 'Unawain kung bakit mahalaga ang e-waste',
      link2Title: 'Hanapin ang Drop-off Points', link2Desc: 'Hanapin ang pinakamalapit na koleksyon',
      link3Title: 'Mag-rehistro ng E-Waste', link3Desc: 'Simulan ang iyong paglalakbay sa pag-recycle',
      link4Title: 'Tingnan ang Gantimpala', link4Desc: 'Alamin kung magkano ang maaari mong kitain',
    },
    login: {
      welcomeBack: 'Maligayang Pagbabalik',
      subtitle: 'Mag-sign in para subaybayan ang iyong mga e-waste drop at kumita ng gantimpala',
      usernameLabel: 'Username', usernamePlaceholder: 'Ilagay ang iyong username',
      passwordLabel: 'Password', passwordPlaceholder: 'Ilagay ang iyong password',
      signInBtn: 'Mag-sign In', signingIn: 'Nagsi-sign in...',
      noAccount: 'Wala pang account?', registerHere: 'Mag-rehistro dito',
      featuresTitle: 'Mga Tampok',
      feature1: 'Subaybayan ang mga e-waste drop', feature2: 'Bantayan ang mga natanggap na gantimpala', feature3: 'Tingnan ang kasaysayan ng koleksyon',
      trackImpact: '📊 Subaybayan ang Epekto', trackImpactDesc: 'Bantayan ang iyong mga e-waste drop at gantimpala',
      earnRewards: '💰 Kumita ng Gantimpala', earnRewardsDesc: 'Makakuha ng ₱5 bawat kilo ng e-waste',
      helpEnv: '🌍 Tulungan ang Kalikasan', helpEnvDesc: 'Maging bahagi ng solusyon',
    },
    register: {
      titleLoggedIn: 'Mag-ulat ng E-Waste', titleNew: 'Mag-rehistro - E-Cycle Hub',
      ewasteSection: 'Mga Detalye ng E-Waste', optional: '(Opsyonal)',
      optionalNote: 'Maaari kang mag-ulat ng e-waste ngayon o mamaya mula sa iyong dashboard.',
      selectDropoff: 'Piliin ang Lokasyon ng Drop-off', weight: 'Timbang (kg)', selectEwaste: 'Piliin ang Uri ng E-Waste',
      accountSection: 'Mga Kredensyal ng Account (Kinakailangan)',
      firstName: 'Pangalan *', lastName: 'Apelyido *', username: 'Username *',
      email: 'Email *', password: 'Password *', confirmPassword: 'Kumpirmahin ang Password *',
      securityAnswer: 'Sagot sa Seguridad *',
      consent: 'Sumasang-ayon ako sa mga tuntunin ng pagproseso ng e-waste.',
      submitEwaste: 'Isumite ang Rekord ng E-Waste', completeReg: 'Kumpletuhin ang Pagpaparehistro', processing: 'Pinoproseso...',
    },
    dashboard: {
      title: 'Dashboard', welcome: 'Maligayang pagdating,', logout: 'Mag-logout',
      logoutConfirm: 'Mag-logout?', logoutText: 'Sigurado ka bang gusto mong mag-logout?', logoutYes: 'Oo, mag-logout',
      totalDrops: 'Kabuuang Drops', ewasteItems: 'mga e-waste',
      totalWeight: 'Kabuuang Timbang', recycled: 'na-recycle',
      totalRewards: 'Kabuuang Gantimpala', earned: 'nakuha',
      envImpact: 'Epekto sa Kalikasan', co2Saved: 'kg CO₂ na natipid',
      dropHistory: 'Kasaysayan ng Iyong Drops',
      noDrops: 'Wala pang mga isinumiteng e-waste.', noDropsHint: 'Gamitin ang pindutan ng Bagong Drop-off para magsimula!',
      type: 'Uri', weight: 'Timbang', date: 'Petsa', location: 'Lokasyon', reward: 'Gantimpala', status: 'Katayuan',
      quickActions: 'Mabilis na Aksyon',
      newDropoff: 'Bagong Drop-off', newDropoffDesc: 'Mag-rehistro ng e-waste',
      findLocation: 'Hanapin ang Lokasyon', findLocationDesc: 'Pinakamalapit na drop-off',
      viewRewards: 'Tingnan ang Gantimpala', viewRewardsDesc: 'Mga detalye ng gantimpala',
      updates: 'Mga Update', updatesDesc: 'Pinakabagong balita',
    },
    updates: {
      title: 'Mga Update at Anunsyo sa Koleksyon',
      subtitle: 'Manatiling updated tungkol sa mga iskedyul ng koleksyon at mahahalagang abiso',
      all: 'Lahat ng Update', collection: 'Koleksyon', notices: 'Mga Abiso', announcements: 'Mga Anunsyo',
      noAnnouncements: 'Walang mga anunsyo sa ngayon. Bumalik muli mamaya!',
      tip: '💡 Tip:', tipText: 'Sundan ang aming Facebook page ng Barangay para sa mga real-time na update at anunsyo.',
    },
    education: {
      title: 'Ano ang E-Waste?',
      subtitle: 'Matuto tungkol sa electronic waste at kung bakit mahalaga ang responsableng pag-recycle',
      faq1Q: 'Bakit mapanganib ang e-waste?',
      faq1A: 'Ang e-waste ay naglalaman ng mga nakakalason na materyales tulad ng tingga, mercury, at cadmium na maaaring mag-kontamina ng lupa at tubig. Kapag hindi wastong itinatapon, ang mga lason na ito ay nakakasama sa mga ecosystem at kalusugan ng tao. Ang maling pagsusunog ay naglalabas ng mapanganib na gas, at ang mga basurahan ay nagtatago ng mga kemikal sa tubig sa lupa. Ang responsableng pag-recycle ay pumipigil sa pinsala sa kalikasan at nakakabawi ng mahahalagang materyales.',
      faq2Q: 'Ano ang nangyayari kapag ang e-waste ay na-recycle nang tama?',
      faq2A: 'Ang tamang pag-recycle ay nakakabawi ng mahahalagang materyales tulad ng ginto, tanso, at mga bihirang elementong lupa para sa muling paggamit. Ang mga nakakalason na bahagi ay ligtas na hinahawakan at itinatatapon. Nababawasan nito ang pangangailangan sa pagmimina, nakatitipid ng enerhiya, at pumipigil sa polusyon sa kalikasan. Ang mga na-recycle na materyales ay ginagamit sa paggawa ng mga bagong electronics, lumilikha ng circular economy.',
      faq3Q: 'Alam mo ba?',
      faq3A: 'Ang isang milyong smartphone ay naglalaman ng 35 beses na mas maraming tanso kaysa sa isang tonelada ng tanso na ore. Ang pag-recycle ng isang milyong laptop ay nakakatipid ng enerhiya na katumbas ng pagpapagana ng 3,500 tahanan sa loob ng isang taon. Ang e-waste ang pinakamabilis na lumalagong basura sa buong mundo, na may higit sa 50 milyong tonelada na nalilikha bawat taon.',
      stat1Title: '50+ Milyong Tonelada', stat1Desc: 'E-waste na nalilikha sa buong mundo bawat taon',
      stat2Title: '₱57 Bilyon', stat2Desc: 'Halaga ng mga materyales sa global na e-waste',
      stat3Title: '3,500 Tahanan', stat3Desc: 'Enerhiyang natipid sa pag-recycle ng 1M laptop bawat taon',
    },
    map: {
      title: 'Mga Lokasyon ng Drop-off',
      subtitle: 'Hanapin ang pinakamalapit na punto ng koleksyon at tingnan ang mga iskedyul',
      locations: 'Mga Lokasyon',
      allLocations: 'Lahat ng Lokasyon',
      loading: 'Nilo-load ang mapa...',
      address: 'Address',
      schedule: 'Iskedyul',
      tip: '📢 Tip:', tipText: 'Tingnan ang aming pahina ng mga update para sa mga pagbabago sa iskedyul at mga anunsyo.',
    },
    incentives: {
      title: 'Mga Insentibo at Gantimpala ♻️',
      subtitle: 'Kumita ng gantimpala para sa bawat kilo ng e-waste na iyong responsableng ini-recycle sa Barangay Burol 1',
      rewardTitle: 'Programa ng Gantimpala',
      rewardUnit: 'bawat kilo ng e-waste',
      rewardDesc: 'Para sa bawat 1 kilogram ng e-waste na iyong ibi-drop off, kikita ka ng ₱5 o katumbas na voucher na maaaring gamitin para sa mga serbisyo ng komunidad.',
      howToTitle: 'Paano Mag-claim',
      step1: 'Irehistro ang iyong e-waste drop-off sa pamamagitan ng aming form',
      step2: 'Magbigay ng tumpak na impormasyon sa timbang',
      step3: 'Tumanggap ng iyong reward certificate',
      step4: 'I-claim ang iyong ₱5 voucher bawat kilo sa Barangay Hall',
      step5: 'Gamitin ang iyong voucher para sa mga programa o serbisyo ng komunidad',
      termsTitle: 'Mga Tuntunin at Kondisyon',
      term1: 'Ang mga gantimpala ay valid sa loob ng 12 buwan mula sa petsa ng pagbibigay',
      term2: 'Minimum na timbang para sa pag-claim ng gantimpala: 0.5 kg',
      term3: 'Tinatanggap: Mga Telepono, Laptop, Charger, at Baterya',
      term4: 'Isang pagpaparehistro lamang bawat drop-off session',
      term5: 'Ang mga voucher ay hindi maaaring ilipat o ibalik',
      term6: 'Ang Barangay ay may karapatang i-verify ang kondisyon ng e-waste',
      calcTitle: 'Kalkulahin ang Iyong Gantimpala 💰',
      calcLabel: 'Ilagay ang timbang (kg):',
      calcBtn: 'Kalkulahin',
      calcWeight: 'Timbang:', calcRate: 'Rate:', calcTotal: 'Kabuuang Gantimpala:',
      tip: '💡 Tip:', tipText: 'Mangolekta ng e-waste mula sa iyong pamilya at mga kaibigan sa Burol 1 para mapakinabangan ang iyong mga gantimpala! Bawat kilo ay mahalaga.',
      invalidWeight: 'Mangyaring maglagay ng wastong timbang sa kilo',
    },
    adminLogin: {
      title: 'Admin Access',
      subtitle: 'Barangay Burol 1 — Restricted Area',
      usernamePlaceholder: 'Admin Username',
      passwordPlaceholder: 'Admin Password',
      loginBtn: 'Mag-login',
      verifying: 'Bine-verify...',
    },
    footer: {
      tagline: 'Nagtataguyod ng responsableng pag-recycle ng e-waste at pagpapanatili ng kalikasan sa ating komunidad.',
      contactTitle: 'Impormasyon sa Pakikipag-ugnayan',
      location: 'Lokasyon', locationValue: 'Burol 1 Dasmarinas Cavite',
      phone: 'Telepono',
      barangayHall: 'Barangay Hall', barangayHallValue: 'Burol 1 Dasmarinas Cavite',
      followUs: 'Sundan Kami',
      socialText: 'Bisitahin ang aming Facebook page ng Barangay para sa mga update at anunsyo',
      partners: 'Mga Kasosyo',
      partner1: 'Pamahalaan ng Barangay', partner2: 'Tanggapan ng Kalikasan', partner3: 'Mga Organisasyon ng Komunidad',
      disclaimer: 'Disclaimer:', disclaimerText: 'Ang website na ito ay nagbibigay ng impormasyon tungkol sa pag-recycle ng e-waste at mga serbisyo ng koleksyon. Para sa mga opisyal na anunsyo at update, mangyaring sumangguni sa Barangay Hall o mga opisyal na social media channel.',
      poweredBy: 'Pinapatakbo ng:', copyright: '© 2024 E-Cycle Hub. Lahat ng karapatan ay nakalaan.',
    },
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'fil' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}